### ISSUE TITLE
Upgrading foundation-cli 2.1.0 → 2.2.1 writes to /usr/lib/ instead /usr/local/lib/

### ISSUE THREAD

**Issue by Moonbase59** [foundation/foundation-cli#58] opened 2017-04-22 12:08 UTC
I already posted this on the forums, but maybe it is more appropriate here:
http://foundation.zurb.com/forum/posts/52302-upgrading-foundation-cli-from-210--221-fails

Hi there!

I decided to check out the new building blocks, so I apparently needed to upgrade my foundation-cli which somehow fails. Before and after I get shown I have 2.1.0 still:

```bash
$ foundation -v
Foundation CLI version 2.1.0
```

I tried the following commands, all giving no npm errors:

```bash
$ sudo npm update -g foundation-cli
$ sudo npm install -g foundation-cli@2.2.1
```

Any idea what’s happening? (I run Ubuntu Studio 14.04.5 LTS on my dev machine.)

---

After some more debugging, I found this:

```bash
$ sudo npm uninstall -g foundation-cli
unbuild foundation-cli@2.2.1

$ sudo npm install -g foundation-cli@2.2.1
/usr/bin/foundation -> /usr/lib/node_modules/foundation-cli/bin/foundation.js
foundation-cli@2.2.1 /usr/lib/node_modules/foundation-cli
├── is-root@1.0.0
├── colors@1.1.2
├── semver@4.3.6
├── nopt@3.0.6 (abbrev@1.1.0)
├── which@1.2.14 (isexe@2.0.0)
├── string-length@1.0.1 (strip-ansi@3.0.1)
├── multiline@1.0.2 (strip-indent@1.0.1)
├── paint-by-number@1.0.0 (chalk@1.1.3)
├── rimraf@2.6.1 (glob@7.1.1)
├── js-yaml@3.8.3 (esprima@3.1.3, argparse@1.0.9)
├── async@2.3.0
├── update-notifier@0.2.2 (is-npm@1.0.0, semver-diff@2.1.0, chalk@0.5.1, configstore@0.3.2, latest-version@1.0.1)
├── inquirer@0.8.5 (ansi-regex@1.1.1, through@2.3.8, figures@1.7.0, cli-width@1.1.1, readline2@0.1.1, chalk@1.1.3, lodash@3.10.1, rx@2.5.3)
├── lodash@4.17.4
├── npm@2.15.12
└── bower@1.8.0

$ foundation -v
Foundation CLI version 2.1.0

$ which foundation 
/usr/local/bin/foundation

$ ls -la /usr/local/bin/foundation 
lrwxrwxrwx 1 root root 52 Mär 11 16:18 /usr/local/bin/foundation -> ../lib/node_modules/foundation-cli/bin/foundation.js
```

I wonder what to do now without breaking customer sites, because for whatever reason I now have got a `node-modules/foundation-cli` _both_ under `/usr/local/lib/` _and_ `/usr/lib/`. The one under `usr/lib/` has the `package.json` with `"version": "2.2.1"` in it, while the system seems to prefer the one under `/usr/local/lib` (which has v2.1.0 in it’s package.json).

I _think_ one of the updates or installs must have broken it. My `/usr/lib` is much more populated than `/usr/local/lib` and I’d actually prefer foundation being installed under `/usr/lib`.

My `/usr/lib/node_modules` has:
```bash
$ ls -la
insgesamt 48
drwxr-xr-x   4 root   root      4096 Apr 21 22:52 .
drwxr-xr-x 246 root   root     36864 Apr 18 11:17 ..
drwxr-xr-x   5 nobody matthias  4096 Apr 21 22:52 foundation-cli
drwxr-xr-x   9 root   root      4096 Apr  5 11:36 npm
```
and my `/usr/local/lib/node_modules` has:
```bash
$ ls -la
insgesamt 16
drwxr-xr-x  4 nobody matthias 4096 Mär 11 16:18 .
drwxr-xr-x 10 root   root     4096 Nov 22 21:02 ..
drwxr-xr-x  5 nobody matthias 4096 Mär 11 16:18 foundation-cli
drwxr-xr-x  8 nobody matthias 4096 Jul 26  2015 markdown-pdf
```

_Can anyone knowledgeable please put me right? **THANK YOU!**_

**Comment by Moonbase59** [comment] 2017-04-22 13:03
I still wonder how this happened and would like an explanation—for the benefit of others.

Nevertheless, for the time being, removing `/usr/local/lib/node_modules/foundation-cli` and `/usr/local/bin/foundation` seemed to cure it:

```bash
$ sudo rm -rf /usr/local/lib/node_modules/foundation-cli/
$ sudo rm /usr/local/bin/foundation
```

**Comment by paxperscientiam** [comment] 2017-04-22 15:13
Hello. Just for clarification, what is the value of your global prefix variable? `/usr/local/` or `/usr/`?

Is there any chance you did a local install of foundation-cli accidentally?

**Comment by Moonbase59** [comment] 2017-04-23 05:46
Q1:
```bash
$ sudo npm config get prefix
/usr
```

Q2: I _think_ not. The only other thing I did lately was to do a `foundation update` within two of my project folders, which updated Foundation from 6.3.0 to 6.3.1.

**Comment by HansUXdev** [comment] 2020-06-26 18:53
@Moonbase59  Hey was this solved?

**Comment by DanielRuf** [comment] 2020-06-26 20:22
Probably yes, closing.
In general people should never use `sudo` which was probably the cause.
This was a permission chaos in old npm versions which required sudo for everything when you have it used once. The npm team has fixed this in the latest releases to use the current user instead of root.

**Closed by DanielRuf** 2020-06-26 20:22 UTC
